apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-uqvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-uqvp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-uqvp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-uqvp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-uqvp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbsf-tenant/rhtap-demo-app/hacbs-test-project-uqvp@sha256:a56de9763e40d402a757e3cfce8573f8b5948fc490aa4cf8d93aec5a0142925f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
